### ISSUE TITLE
It just don't work 

### ISSUE THREAD

**Issue by Klairm** [ajmeese7/spambot#11]
I run node bot.js and the message Ready to up level! apparear, but in the server i type /spam, and nothing happens

https://gyazo.com/b263b26fab2cc810807813114771cfa4

**Comment by ajmeese7** [comment]
Hey Klairm. Sorry you're having issues. Can you try installing Node v9.0.0 and tell me if that works for you? I changed the code today and tested it on my PC with that version and it worked for me. If that doesn't work get back to me and I'll see what I can do. Also, did you do all the stuff the README says like adding your login token and running `npm install`?

Sorry if these questions seem stupid, but I need as much information as you can give me so I can do my best to help.

**Comment by Klairm** [comment]
I did all from readme, about node v9.0.0 i can't find it xD i only can find v8 and v10, (i have the version 8)

**Comment by Klairm** [comment]
Now i tried with the v10, but when i do npm install say i need dependencies : 
https://gyazo.com/391d23348ca1ad22ee83539496833f0e

In linux i know how to download dependences, but idk how to do it on windows xD

**Comment by ajmeese7** [comment]
Those warnings should be able to be safely ignored. I had those appear on Linux but it ran without me addressing them. Try cloning the latest code then installing and running it without worrying about the warnings and let me know if it runs

**Comment by Klairm** [comment]
Still don't working, just the same as before, it says Ready to level up!, the bot apprear online on the server but i wirte /spam and nothing happens

**Comment by ajmeese7** [comment]
Oh that's the problem. You're supposed to run it from your account, not from a bot. This is a selfbot, which is different from a regular bot

**Comment by Klairm** [comment]
wyd about running from my account? I'm running from my acc, and i invited the bot on the server, (i thought it's necessary the bot on the server)

**Comment by Klairm** [comment]
Ohhh now i know what you mean, i need put my acc token, now my problem is, in application i don't found my token

**Comment by ajmeese7** [comment]
Ok go to discordapp.com, sign in, press CTRL+Shift+I, go to storage, local storage, then copy the line that says `token`

**Comment by ajmeese7** [comment]
For some reason I can no longer find the token in the Discord desktop app either. I'll update the README to reflect that

**Comment by Klairm** [comment]
Thanks you a lot!! Now it works ^.^ 

I'm just retarded and i was putting a bot token and not my acc token xD

**Comment by Klairm** [comment]
Btw, wouldn't be more easy and unabanable use a script keyboard for spam messages? I have one script which do that xD

**Comment by Klairm** [comment]
Thx for the help ;)

**Comment by ajmeese7** [comment]
No problem :) I could've done a keyboard script, but I'm usually using my computer for other things when I'm running the spam command so I didn't want to interfere with that. If you like the program, I'd really appreciate it if you left a [star](https://github.com/ajmeese7/spambot/stargazers)!
