### ISSUE TITLE
Syntax Error: Unexpected Token <<

### ISSUE THREAD

**Issue by thepchamp** [ajmeese7/spambot#16]
I have followed your guide 100% did everything and still I couldn't get the bot to work. No matter what I do it just never gets started. Token error even though I have provided the correct token.
![Screenshot_1](https://user-images.githubusercontent.com/49122862/55290597-8c23f780-53ee-11e9-8c1a-7f3866db2c9a.png)

**Comment by thepchamp** [comment]
can i have your discord? we can chat there if you want.

**Comment by ajmeese7** [comment]
This is a new one for me. My Discord is ajmeese7#4835 if you still need help

**Comment by ajmeese7** [comment]
This is a new one for me. My Discord is ajmeese7#4835 if you still need help

**Comment by thepchamp** [comment]
yeah I'd like the issue to be resolved. I've sent the friend request there thanks.

**Comment by ajmeese7** [comment]
Issue resolved with commit 7dd9a6
