### ISSUE TITLE
24 hours 

### ISSUE THREAD

**Issue by uCheater** [ajmeese7/spambot#17]
hi i wanted to thank you for this amazing bot
i wanted to ask u if i can upload it on heroku and make it working 24 hours but it didnt work
if u can tell me how or give me a tutorial for that pls thank you again !

**Comment by ajmeese7** [comment]
If you want to upload something to Heroku, there is mandatory downtime for the free tier of apps. You would have to upgrade to a paid plan, which I am not sure if you are willing to do. It would likely be much more cost-efficient to have the program running 24/7 from a Raspberry Pi Zero, which can go for $5 depending on your retailer. They consume very little power and you would hardly notice the difference in your electricity bill. Closing this for now, but if you are genuinely willing to pay for 24/7 hosting on Heroku I will be willing to reopen this and help you configure it for anybody who wants to attempt something similar in the future.

If this has helped you at all, please leave a star to show your support of the project :)
