### ISSUE TITLE
Not an issue but a question 

### ISSUE THREAD

**Issue by Creyni** [ajmeese7/spambot#19]
Hi there @ajmeese7

so i got it to work finally so yay!! for me lol

however i have some questions.

is there a list of commands? or is it just the /spam to start it.

are certain things editable about bot? I would like to remove the auto prune and perhaps speed the bot up very slightly but i dont have the first clue who i would do these. And increase the 10k spam limit

**Comment by ajmeese7** [comment]
Everything is editable via the bot.js file, but if you would like I can look into instituting a command line interface to handle that for you.

The only command currently is the spam command to start the bot. See #13 for information regarding the prune command and the fourth paragraph of the README for info on changing the bot speed

**Comment by Creyni** [comment]
Thank you for your advice, i realised about the speed after commenting and forgot to edit it out lol.

just trying to make make it as lag free as possibke when running on multiple servers so hoping the prune command being removed would help with that. A command interface wiuld be amazing seeing as thisbis the only soam bot i have managed to understand enough to get running i plan on using it alot lol

**Comment by ajmeese7** [comment]
I am on vacation right now but I will get to it as soon as I can. Will close this issue after I make the relevant PR

**Comment by ajmeese7** [comment]
Added with e1e83e058ed15e65ebac61509e602b06b7db99d7. Feel free to create another issue with more ideas that would make your life easier, but please try to keep the formatting of your messages professional in the future 😄 since you like this project so much, you could leave a star to show your appreciation. Cheers 🎉
