### ISSUE TITLE
Bot not working for me :(

### ISSUE THREAD

**Issue by UnknownAgent** [ajmeese7/spambot#29]
When I ran the bot, I am only getting a message 'Ready to level up' and no node connection. The command /spam is not working but the bot is online... Also, when downloading node.js it is showing that I have to install peer dependiencies myself so i did that by typing 'npm install @discordjs/uws@^10.149.0.' Here is everything i did - 
![image](https://user-images.githubusercontent.com/67637042/86121435-9baf5600-baf3-11ea-995e-f510adc97181.png)

-My screen freezes after Ready to level up and on my discord it is unresponsive to /spam.
-pls help

**Comment by ajmeese7** [comment]
The warning isn't required, so you can safely ignore the `npm install @discordjs/uws@^10.149.0`. I just made some changes to the code that may help with your issue, so try downloading the latest code, doing `npm install` without installing the other dependency, and let me know how that goes. Cheers!

**Comment by UnknownAgent** [comment]
I am getting the same issue again - the screen freezes at Ready to level up! and the /spam command doesn't work. 
![image](https://user-images.githubusercontent.com/67637042/86197844-e07ad180-bb73-11ea-9ef7-b6832e71db7f.png) Pls help as I really need to level up my Dank Memer account very quickly.

**Comment by ajmeese7** [comment]
This doesn't work on a bot, this is a selfbot that you use on a user account. It might be possible to get this to work for a bot but I have never tried it. If you want to get it to work for a user account, send me a picture of your `config.json` so I can make sure you are using the proper prefix for the command.

**Comment by UnknownAgent** [comment]
Yes its working!!! Thank You!!! However, I am not able to control the messages.  
![image](https://user-images.githubusercontent.com/67637042/86311552-459af980-bc3e-11ea-9efb-a8dc722fdf96.png) As u can see the message is pls beg but it is showing spam message 1

**Comment by ajmeese7** [comment]
I just fixed this in 1c898c7. Download the latest code and give it a shot! Sorry it took so long, I spent the weekend with my family. Cheers!

**Comment by t-trafer** [comment]
hey, i'd love to get some assistance from you on a similar project i'm thinking of
would you mind?

**Comment by ajmeese7** [comment]
@t-trafer I'd love to help! Drop a link to your repository and I'll take a look. Feel free to PM me at ajmeese7#4835 on Discord if you want to talk about anything in specific. Cheers!
