### ISSUE TITLE
async function without catch block

### ISSUE THREAD

**Issue by hieu2010** [ajmeese7/spambot#3]
(node:7512) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.16.58.5:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
(node:7512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by ajmeese7** [comment]
Do you have any ideas on how to write a catch block for this? I can take a look when I'm on my laptop later but I feel like it should be pretty simple.

Did this just randomly pop up in your terminal when the program was running or was this the first thing that appeared when you ran the program?

**Comment by hieu2010** [comment]
popped up while the spambot was running. Did a catch block now with 
.catch(error => sendSpamMessage);

and apparently i dont get any error msgs anymore. All good on my side now

**Comment by ajmeese7** [comment]
Sweet. You could make a PR if you want so nobody else has to deal with this issue

**Comment by hieu2010** [comment]
I kind of reworked your script, removing the prune and delete msgs so that the bot just keep on spamming the chat^^ I don't think a PR is suitable in this case

**Comment by ajmeese7** [comment]
Just PR whenever and I'll merge it

**Comment by ajmeese7** [comment]
I just went ahead and added it
