### ISSUE TITLE
multi accounts

### ISSUE THREAD

**Issue by KuroizakiKun** [ajmeese7/spambot#32]
can we add more than 1 account in (config.json)? like this?
![Screenshot_1](https://user-images.githubusercontent.com/38588879/90628817-795ecc80-e248-11ea-87d8-e93955205125.png)

**Comment by ajmeese7** [comment]
That is not yet a feature of this project. Would you like me to see if I can add it in?

**Comment by ajmeese7** [comment]
![Multiple accounts](https://user-images.githubusercontent.com/17814535/90648249-e77ea180-e1fe-11ea-95e7-450968c29357.png)

Just added in this feature. Hope this is what you were looking for, cheers! Feel free to reach out if there's anything else you would like to see, or if you think I can improve this feature in any way.
