### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Perditrix** [ajmeese7/spambot#48]
When i try to run this is what i get 
![error](https://user-images.githubusercontent.com/64577386/120212400-87745b80-c264-11eb-8ac8-94aa878d5b4d.png)

**Comment by ajmeese7** [comment]
what does your `config.json` look like?

**Comment by mystcuro** [comment]
Most probably he kept the 2nd element of botToken array as it was in config.json file.

By the way I haven't executed this program yet, was looking at your code. Nice work! This code smells good, Simple, Clean and easily readable code! I was feeling like reading my own codes.

**Comment by Perditrix** [comment]
> what does your `config.json` look like?
{
  "botToken": "TOKEN"
  "prefix": "/"
}
exactly that but the TOKEN is my actual token

**Comment by mystcuro** [comment]
> > what does your `config.json` look like?
> {
>   "botToken": "TOKEN"
>   "prefix": "/"
> }
> exactly that but the TOKEN is my actual token
> 

Put a comma (,) after your token: 

 {
   "botToken": "TOKEN",
   "prefix": "/"
 }

**Comment by ajmeese7** [comment]
@Perditrix mystcuro is correct, you need the comma at the end of the `botToken` line. Please let me know if this resolves your issue :)
