### ISSUE TITLE
Multithreading?

### ISSUE THREAD

**Issue by byk3nko** [ajmeese7/spambot#49]
Can I write tokens in config.json and list them to run all of them at the same time? I write !Start, and so that all authorized 'bots' start spamming to the channel where I sent the first message. I have already added several tokens, but I have to start from each (! Start), otherwise it does not work

**Comment by ajmeese7** [comment]
Do you have your tokens in an array in the `config.json` file? If I'm understanding your request correctly, you just want the bot to spam on each account when you run the command, yes? Or are you saying you don't want to run the command on each individual account, you want them to all start with a command from one account?

**Comment by byk3nko** [comment]
Yes. You understood correctly.

**Comment by ajmeese7** [comment]
You would have to modify the code to login with the account you want to send the command from, then have a loop inside of that listener to login to all the other bots and send the messages. Something along the lines of the following:

`config.json`:
```json
{
  "primaryAccount": "YOUR_PRIMARY_TOKEN_HERE",
  "alternateAccounts": [ "YOUR_ALTERNATE_ONE_TOKEN_HERE", "YOUR_ALTERNATE_TWO_TOKEN_HERE" ],
  "prefix": "!"
}
```

`bot.js`:
```javascript
const { Client } = require('discord.js');
const config = require('./config.json');
const allTokens = config.alternateAccounts.concat(config.primaryAccount);

process.on('unhandledRejection', error => {
  console.error(
    "There was an error! Did you update the config.json file? " +
    "If you did, let me know what the error message says in an issue on the repo on GitHub. \n",
    error
  );
  process.exit();
});

console.log("Ready to level up!");
var timeToWait = null, minTime = 2000, maxTime = 4350;

const client = new Client();
client.config = config;
client.login(config.primaryAccount);

client.on("message", async message => {
  // Ignore message if the content doesn't apply to us
  if (message.author.id !== client.user.id || message.content.indexOf(client.config.prefix) !== 0) return;

  const prefix = config.prefix;
  const args = message.content.slice(prefix.length).trim().split(/ +/g);
  const command = args.shift().toLowerCase();
  if (command !== "spam") return;

  for (const token of allTokens) {
    try {
      function sendSpamMessage() {
        client.login(token);
        message.channel.send("This is a spam message!");
        timeToWait = Math.floor(Math.random() * (maxTime - minTime)) + minTime;
        setTimeout(sendSpamMessage, timeToWait);
      }

      sendSpamMessage();
    } catch (error) {
      console.error("CAUGHT ERROR =>", error);
    }
  }
})
```

I just tested it out on two of my accounts and it worked great, let me know if this helps :)

**Comment by byk3nko** [comment]
Yes. Thank you so much for your quick response and help.
