### ISSUE TITLE
Cannot find module 'discord.js' and npm install error

### ISSUE THREAD

**Issue by 999Ecstasy** [ajmeese7/spambot#54]
![Przechwytywanie](https://user-images.githubusercontent.com/89463883/130626554-3c41ed4f-7d9a-4108-bcbf-eca233b4152d.PNG)
![npm install error](https://user-images.githubusercontent.com/89463883/130626663-6a06627b-3c93-4c03-8423-a3756362a1c7.PNG)

**Comment by ajmeese7** [comment]
I recommend following the instructions in one of the answers in this thread: https://stackoverflow.com/q/20666989/6456163

The problem is you have not added git to your Windows PATH, please let me know if there is anything else I can help you with :)

**Comment by 999Ecstasy** [comment]
yes

**Comment by ajmeese7** [comment]
Then I'm not sure what to tell you my man, the library says your token isn't valid

**Comment by 999Ecstasy** [comment]
my config looks like this
![Przechwytywanie](https://user-images.githubusercontent.com/89463883/130639960-8419e911-7cee-4896-8714-9ca3efe413c2.PNG)

**Comment by 999Ecstasy** [comment]
it's good?

**Comment by ajmeese7** [comment]
You need to remove the empty parenthesis if you do not want to use a second account, and the comma following the first set of parenthesis. That's the issue :) it's reading the empty parenthesis as an additional account currently

**Comment by 999Ecstasy** [comment]
done and new problem 😃
![23](https://user-images.githubusercontent.com/89463883/130641575-ffaf6895-52f7-4e42-8d14-16383c0a8d71.PNG)

**Comment by ajmeese7** [comment]
What does your configuration file look like now?

**Comment by 999Ecstasy** [comment]
the token is changed to show you
![234](https://user-images.githubusercontent.com/89463883/130642613-6bcc1f6d-4c62-43aa-8983-32769feb2402.PNG)

**Comment by ajmeese7** [comment]
Alright let's try something weird, if it works I can implement it as a legitimate fix and if not we can try something else.

Go into that `src/client/websocket/packets/handlers/Ready.js` file, go down to line 41, and change the condition to `note && !note.length` instead of just `!note.length`. Then save your changes and run it again and let me know what happens

**Comment by 999Ecstasy** [comment]
its working thx bro I respect you ❤️

**Comment by ajmeese7** [comment]
Alright bet I'll implement the real fix now, I'm happy I could help :)
