### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by Lamukurina** [ajmeese7/spambot#66]
Hello. I think it might honestly just be a me problem but once i do npm install do i just have to take the config.json and just edit it myself on another window before entering it in the terminal? and if possible can i seek your advice on discord as im really awful at this :(

**Comment by ajmeese7** [comment]
Hey @Lamukurina, to edit the `config.json` file you just need to open it in the text editor of your choice and modify the information as described in the README. Examples of text editors that you can use to accomplish this task include Notepad, Notepad++, VS Code, and Atom.

**Comment by Lamukurina** [comment]
Right! @ajmeese7 thank you so much! after i edit it in VS code im not exactly sure what to do though. Do i just reopen the terminal folder i put the code in? or what do i do after editing the config.json in VS? Once again sorry for being terrible at this

**Comment by ajmeese7** [comment]
@Lamukurina after editing the `config.json` you need to save your changes then the program should be good to go :)

**Comment by Lamukurina** [comment]
Now it cant find the module ahhhh im just gonna email you asking for help and showing you my issue if that's fine with you?

**Comment by ajmeese7** [comment]
Sure thing @Lamukurina if I can find a good extensible solution to offer you I will come back to this issue and post it, for now I am going to close this issue.
