### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by RidhoNGPX** [ajmeese7/spambot#72]
![Screenshot_20230116-155134_Termux](https://user-images.githubusercontent.com/89362181/212636607-ebc96e00-a290-489a-a985-50a84bf50d8b.png)
eror bro

**Comment by ajmeese7** [comment]
There was a change to the Discord API, I have updated my fork of the Discord.js library (https://github.com/discordjs/discord.js/commit/df1474303ca5df1c18eb7baa5ef6e682e70e453d), which is a dependency of this project. Please run `npm update` to download the latest version of the dependencies and your problem should be solved.

**Comment by RidhoNGPX** [comment]
> There was a change to the Discord API, I have updated my fork of the Discord.js library ([discordjs/discord.js@df14743](https://github.com/discordjs/discord.js/commit/df1474303ca5df1c18eb7baa5ef6e682e70e453d)), which is a dependency of this project. Please run `npm update` to download the latest version of the dependencies and your problem should be solved.

thanks the problem has been resolved
