### ISSUE TITLE
eror again bro

### ISSUE THREAD

**Issue by RidhoNGPX** [ajmeese7/spambot#73]
![Screenshot_20230118-080355_Termux](https://user-images.githubusercontent.com/89362181/213055433-12685088-f2a9-4811-9192-9c1ab6bbf879.png)

**Comment by ridx807** [comment]
> ![Screenshot_20230118-080355_Termux](https://user-images.githubusercontent.com/89362181/213055433-12685088-f2a9-4811-9192-9c1ab6bbf879.png)

Solved by delete node_modules and installing fresh discord.js
```npm install discord.js```

**Comment by ridx807** [comment]
Sama bro, solved belum?

**Comment by ajmeese7** [comment]
Closing as duplicate of #74, even though this one was made first that one has text instead of an image.
