### ISSUE TITLE
projects folder?

### ISSUE THREAD

**Issue by miraclmayhem** [ajmeese7/spambot#8]
im having a tough time finding this folder? any suggestions?

**Comment by ajmeese7** [comment]
Your projects folder is simply wherever you want to work on this project. You could clone the repository in your downloads folder and work on it there if you wanted to

**Comment by miraclmayhem** [comment]
good shit, thanks

**Comment by ajmeese7** [comment]
Glad I could help. Thanks for using my bot! If you really like it, consider leaving a [star](https://github.com/ajmeese7/spambot/stargazers) :)
